#! /bin/bash          

INSTALLSIZE=100
INSTALLDISK=()

while read disk size
do          

#Remove the Letter from sizes
if [[ $size =~ [G] ]] ; then
	BARE_SIZE=${size//G} #remove the G

	RAW_SIZE=$(printf '%d\n' $BARE_SIZE  2>/dev/null) #Remove the floating points
	echo "DISK: $disk SIZE: $RAW_SIZE "
	echo "size has G in it"

	#Is the disk large enough for install
	if (($RAW_SIZE > $INSTALLSIZE )); then
	
	#If it is large enough to install OS, then add to array
	echo "Disk is greater than $INSTALLSIZE"
	INSTALLDISK+=($disk)

	else
	echo "Disk is smaller that $INSTALLSIZE"
	fi

fi

if [[ $size =~ [M] ]] ; then
echo "size has M in it"
BARE_SIZE=${size//M}
fi

if [[ $size =~ [T] ]] ; then
echo "size has T in it"
BARE_SIZE=${size//T}
fi



done < <(lsblk | egrep "^sd" | awk ' { print $1 " " $4 } ')

echo
echo
echo "Search complete."

for i in "${INSTALLDISK[@]}"
do
echo $i
done

echo "${#INSTALLDISK[@]}"


