#! /bin/bash          

# lsblk -a -b -o NAME,SIZE

#set the size in bytes
#107374182400 is 100G
#100663296 is 96M
#128035676160 is 119G
#1000204886016 is 931G

#1 Byte = 8 Bit
#1 Kilobyte = 1,024 Bytes
#1 Megabyte = 1,048,576 Bytes
#1 Gigabyte = 1,073,741,824 Bytes
#1 Terabyte = 1,099,511,627,776 Bytes

#INSTALLSIZE=107374182400 #100GB
INSTALLSIZE=128849018880 #120GB
INSTALLDISK=()

while read disk size
do          

	RAW_SIZE=$(printf '%d\n' $size  2>/dev/null) #Remove the floating points
	#echo "DISK: $disk SIZE: $RAW_SIZE "

	#Is the disk large enough for install
	if (($RAW_SIZE > $INSTALLSIZE )); then
	
	#If it is large enough to install OS, then add to array
	echo "Disk $disk is greater than $INSTALLSIZE"
	INSTALLDISK+=($disk)

	else
	echo "Disk $disk is smaller that $INSTALLSIZE"
	fi


done < <(lsblk -a -b -o NAME,SIZE | egrep "^sd" | awk ' { print $1 " " $2 } ')
#done < <(lsblk | egrep "^sd" | awk ' { print $1 " " $4 } ')

echo
echo
echo "Search complete."

for i in "${INSTALLDISK[@]}"
do
echo $i
done

echo "${#INSTALLDISK[@]}"


